name: SSL
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=5.9.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - backoff==2.2.1
      - cattrs==25.3.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - docker==7.1.0
      - farama-notifications==0.0.4
      - fastapi==0.121.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gymnasium==1.2.2
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kagglehub==0.3.13
      - kiwisolver==1.4.9
      - lightning==2.5.5
      - lightning-sdk==2025.11.13.post0
      - lightning-utilities==0.15.2
      - litmodels==0.1.8
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - minari==0.5.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - pandas==2.3.3
      - peft==0.18.0
      - pillow==11.3.0
      - prettytable==3.16.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==20.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-cache==1.2.1
      - rich==14.2.0
      - richuru==0.1.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.43.0
      - shellingham==1.5.4
      - simple-term-menu==1.6.6
      - smmap==5.0.2
      - sniffio==1.3.1
      - stable-pretraining==0.1.5.dev37+gccaf93b1a.d20251113
      - starlette==0.49.3
      - submitit==1.5.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - timm==1.0.20
      - tokenizers==0.22.1
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.4.0
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - url-normalize==2.2.1
      - urllib3==2.5.0
      - uv==0.9.7
      - uvicorn==0.38.0
      - wandb==0.22.3
      - websocket-client==1.9.0
      - wget==3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
